export enum Body {
    Sun = 'Sun',
    Moon = 'Moon',
    Mercury = 'Mercury',
    Venus = 'Venus',
    Mars = 'Mars',
    Jupiter = 'Jupiter',
    Saturn = 'Saturn',
    Uranus = 'Uranus',
    Neptune = 'Neptune',
    Pluto = 'Pluto',
    NorthNode = 'North Node',
    SouthNode = 'South Node',
    Ascendant = 'Ascendant',
    MidHeaven = 'Midheaven',
    Vulcain = 'Vulcain',
    Earth = 'Earth',
    Lilith = 'Lilith',
    Ceres = 'Ceres',
    Chiron = 'Chiron',
    EastPoint = 'East Point',
    Fortune = 'Part of Fortune',
    Pallas = 'Pallas',
    Vesta = 'Vesta',
    Juno = 'Juno',
    Vertex = 'Vertex',
}

export enum Sign {
    Aries = 'Ari',
    Taurus = 'Tau',
    Gemini = 'Gem',
    Cancer = 'Can',
    Leo = 'Leo',
    Virgo = 'Vir',
    Libra = 'Lib',
    Scorpio = 'Sco',
    Sagittarius = 'Sag',
    Capricorn = 'Cap',
    Aquarius = 'Aqu',
    Pisces = 'Pis',
}

export enum Aspect {
    Conjunction = 'Conjunction',
    Opposite = 'Opposition',
    Square = 'Square',
    Trine = 'Trine',
    Sextile = 'Sextile',
    Inconjunct = 'Inconjunct',
    SemiSextile = 'Semi-Sextile',
    SemiSquare = 'Semi-Square',
    SesquiQuadrate = 'Sesquiquadrate',
    Quintile = 'Quintile',
}

export const AstroFontBodyMapping: Record<Body | string, string> = {
    [Body.Sun]: "s",
    [Body.Moon]: "a",
    [Body.Mercury]: "f",
    [Body.Venus]: "g",
    [Body.Mars]: "h",
    [Body.Jupiter]: "j",
    [Body.Saturn]: "s", // Wait, Sun and Saturn both "s"? Check user input. Sun is usually 's' or 'S'. Let's stick to user input for now.
    [Body.Uranus]: "F",
    [Body.Neptune]: "G",
    [Body.Pluto]: "J",
    [Body.NorthNode]: "k",
    [Body.SouthNode]: "?",
    [Body.Ascendant]: "1",
    [Body.MidHeaven]: "3",
    [Body.Vulcain]: "V",
    [Body.Earth]: "E",
    [Body.Lilith]: "L",
    [Body.Ceres]: "C",
    [Body.Chiron]: "D",
    [Body.EastPoint]: "2",
    [Body.Fortune]: "L", // Same as Lilith? User input says so.
    [Body.Pallas]: ":",
    [Body.Vesta]: "_",
    [Body.Juno]: ";",
    [Body.Vertex]: "!",
    // Normalize known API names
    'true_node': 'k', // North Node
    'mean_node': 'k',
    'pof': 'L',
    'asc': '1',
    'mc': '3',
}

export const AstroFontSignMapping: Record<Sign | string, string> = {
    [Sign.Aries]: "x",
    [Sign.Taurus]: "c",
    [Sign.Gemini]: "v",
    [Sign.Cancer]: "b",
    [Sign.Leo]: "n",
    [Sign.Virgo]: "m",
    [Sign.Libra]: "X",
    [Sign.Scorpio]: "C",
    [Sign.Sagittarius]: "V",
    [Sign.Capricorn]: "B",
    [Sign.Aquarius]: "N",
    [Sign.Pisces]: "M",
}
